set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /usr/bin/powerpc-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/powerpc-linux-gnu-g++)
set(CMAKE_AR /usr/bin/powerpc-linux-gnu-ar CACHE FILEPATH "" FORCE) 
set(CMAKE_LINKER /usr/bin/powerpc-linux-gnu-ld)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
